variables:
- name: BuildParameters.solution
  value: '**\*.sln'
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Windows
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk '
  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: restore
  - task: NuGetToolInstaller@0
    displayName: Use NuGet 6
    inputs:
      versionSpec: 6
      checkLatest: true
  - task: NuGetCommand@2
    displayName: NuGet restore
    inputs:
      solution: $(BuildParameters.solution)
  - task: VSBuild@1
    displayName: Build solution **\*.sln
    inputs:
      solution: $(BuildParameters.solution)
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
  - task: VSTest@2
    displayName: VsTest - testAssemblies
    inputs:
      testAssemblyVer2: >-
        **\$(BuildConfiguration)\*test*.dll

        !**\obj\**
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
  - task: PublishSymbols@2
    displayName: Publish symbols path
    continueOnError: True
    inputs:
      SearchPattern: '**\bin\**\*.pdb'
      PublishSymbols: false
      SymbolServerType: TeamServices
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    condition: succeededOrFailed()
    inputs:
      SourceFolder: $(system.defaultworkingdirectory)
      Contents: '**\bin\$(BuildConfiguration)\**'
      TargetFolder: $(build.artifactstagingdirectory)
  - task: DotNetCoreCLI@2
    displayName: dotnet pack
    inputs:
      command: pack
      versioningScheme: byPrereleaseNumber
  - task: DotNetCoreCLI@2
    displayName: dotnet push
    inputs:
      command: push
      feedPublish: 405a08ff-e524-4a19-98c6-43d5c1d3560b/9b7c9ef3-4de3-47b4-8d4e-126eb5da5b2f
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
...
